name: Check Markdown Links

on:
  pull_request:
    paths:
      - '**.md'
  push:
    branches:
      - master
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check links in markdown files
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/mlc_config.json'

      - name: Show results
        if: always()
        run: |
          echo "Link check completed. Check the output above for any broken links."
